//top
../../rtl/top.v
../../rtl/ctrl_engine.v
//scheduler
../../rtl/sch/scheduler.v
../../rtl/sch/addr_if.v
../../rtl/sch/sche_sub.v
../../rtl/sch/handshake_sche2pe.v
//PE
../../rtl/pe_array/pe_array.v
../../rtl/pe_array/pe_ic.v
../../rtl/pe_array/pe2.v
../../rtl/pe_array/pe.v
//PU
../../rtl/pu/pu_top.v
../../rtl/pu/pu_adder2.v
../../rtl/pu/pu_adder4.v
../../rtl/pu/pu_bias_add_pipe1.v
../../rtl/pu/pu_ic_add_pipe0.v
../../rtl/pu/pu_mul.v
//../../rtl/pu/pu_relu_mul_pipe2.v
//../../rtl/pu/pu_requant_pipe4.v
../../rtl/pu/pu_resi_add_pipe_p3.v
../../rtl/pu/pu_hbm_pipe.v
../../rtl/pu/pu_lbm_pipe.v
//buf
../../rtl/dp_ram.v
../../rtl/dp_ram_regout.v
../../rtl/wt_buf.v
../../rtl/fe_buf.v
../../rtl/olp_buf.v
../../rtl/param_buf.v
../../rtl/res_buf.v
//tb
//../tb/tb_top.sv
../tb/tb_top_switch.sv
//../tb/sub_bench/task.sv